const money=n=>n===null||n===''?'Price on request':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(n));const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const url=s=>{try{let u=new URL(s);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}};let artworks=[],shown=[];function render(){shown=artworks.filter(r=>r.visible==='yes');document.querySelector('#grid').innerHTML=shown.map(r=>`<article class="art">${url(r.image_url)?`<img loading="lazy" src="${e(url(r.image_url))}" alt="${e(r.title)}" onerror="this.replaceWith(Object.assign(document.createElement('p'),{textContent:'Image unavailable'}))">`:'<p>Image to follow</p>'}<h2>${e(r.title||r.sku)}</h2><p class="meta">${e(r.sku)} · ${e(r.medium)}<br>${e(r.size_unframed)}${r.size_unframed?' inches, unframed':''}${r.size_framed?'<br>'+e(r.size_framed)+' inches, framed':''}</p><p class="price">${money(r.price_usd)} USD</p>${url(r.product_url)?`<a href="${e(url(r.product_url))}">View artwork on Clare’s website ↗</a>`:''}</article>`).join('');}
function printList(){const w=window.open('','_blank');if(!w)return;w.document.write('<!doctype html><title>Clare Stokolosa — Price list</title><style>body{margin:0;background:#f6f3ed;color:#29392f;font:16px system-ui}main{max-width:1100px;margin:auto;padding:40px 24px}header{border-bottom:1px solid #b6bcae;padding-bottom:28px;margin-bottom:32px}h1{font:54px Georgia;margin:8px 0}h2{font:27px Georgia}a{color:#315443}button,.button{background:#315443;color:white;border:0;border-radius:4px;padding:12px 18px;cursor:pointer;text-decoration:none}nav{display:flex;gap:12px;flex-wrap:wrap}.grid{display:grid;grid-template-columns:1fr 1fr;gap:36px}.art img{width:100%;height:360px;object-fit:contain;background:#eae6de}.art{border-bottom:1px solid #ccc;padding-bottom:24px}.meta{color:#596556}.price{font-size:21px}input,textarea,select{font:inherit;padding:8px;border:1px solid #bbb;width:100%;box-sizing:border-box}label{display:block;margin:12px 0}dialog{width:min(600px,85vw);max-height:85vh;overflow:auto}table{border-collapse:collapse;width:100%}td,th{text-align:left;padding:10px;border-bottom:1px solid #ccc}th{font-size:13px}small{color:#596556}@media(max-width:650px){.grid{grid-template-columns:1fr}h1{font-size:39px}.art img{height:300px}}@media print{nav,.controls{display:none}main{padding:0}body{background:white;font-size:11pt}h1{font-size:26pt}tr{break-inside:avoid}thead{display:table-header-group}@page{size:A4;margin:15mm}</style><main><h1>Clare Stokolosa</h1><p>Italy studio · Original prices in USD</p><table><thead><tr><th>SKU</th><th>Artwork</th><th>Medium / Size (inches)</th><th>USD</th></tr></thead><tbody>'+shown.map(r=>'<tr><td>'+e(r.sku)+'</td><td>'+e(r.title)+'</td><td>'+e(r.medium)+'<br>'+e(r.size_unframed)+' unframed'+(r.size_framed?'<br>'+e(r.size_framed)+' framed':'')+'</td><td>'+money(r.price_usd)+'</td></tr>').join('')+'</tbody></table><p>clarestokolosa.com</p></main>');w.document.close();w.focus();w.print();}
async function loadCatalog(){
 const grid=document.querySelector('#grid');
 grid.textContent='Loading artworks…';
 try{
  const response=await fetch('./artworks.json',{cache:'no-store'});
  if(!response.ok)throw Error('Could not load artwork list.');
  const rows=await response.json();
  if(!Array.isArray(rows)||rows.some(r=>typeof r.sku!=='string'||typeof r.title!=='string'||!['yes','no'].includes(r.visible)||!(r.price_usd===null||typeof r.price_usd==='number'&&Number.isFinite(r.price_usd)&&r.price_usd>=0)))throw Error('Please check artwork data.');
  if(new Set(rows.map(r=>r.sku.toUpperCase())).size!==rows.length)throw Error('Duplicate artwork SKU.');
  artworks=rows;render();document.querySelector('#print-button').disabled=false;
 }catch(error){grid.textContent='Artwork list unavailable. Please try again shortly.';console.error(error)}
}
document.querySelector('#print-button').addEventListener('click',printList);
loadCatalog();
